# Generated by Django 5.2.3 on 2025-07-14 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='variation',
        ),
    ]
