# Generated by Django 5.2.3 on 2025-07-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_variation_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='product_name',
            new_name='product',
        ),
    ]
