# Generated by Django 5.2.3 on 2025-07-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='key',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='value',
        ),
        migrations.AddField(
            model_name='specification',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
