# Generated by Django 5.2.3 on 2025-07-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_specification_key_remove_specification_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='group',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SpecificationGroup',
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
