# Generated by Django 5.2.3 on 2025-07-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_specification_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='specification',
            new_name='specifications',
        ),
    ]
