# Generated by Django 5.2.3 on 2025-07-31 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
