# Generated by Django 5.2.3 on 2025-08-10 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_with_this_offer', to='store.offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers_on_this_product', to='store.product'),
        ),
    ]
