# Generated by Django 5.2.3 on 2025-08-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_address_userprofile_delete_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
