# Generated by Django 5.2.3 on 2025-10-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='selling_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
