# Generated by Django 5.2.3 on 2025-10-19 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_highlight_delete_highlights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
    ]
