# Generated by Django 5.2.3 on 2025-11-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_returnrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/default.jpg', null=True, upload_to='profile_photos/'),
        ),
    ]
