# Generated by Django 5.2.3 on 2026-02-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_userprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
