# Generated by Django 5.2.3 on 2026-02-25 01:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_productimages_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
