# Generated by Django 5.2.3 on 2026-04-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_wallettransaction_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('wallet_recharge', 'Wallet Recharge'), ('order_payment', 'Order Payment'), ('refund', 'Refund'), ('signup_bonus', 'Signup Bonus'), ('referral_bonus', 'Referral Bonus')], max_length=20),
        ),
    ]
