# Generated by Django 5.2.3 on 2026-04-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_orderitem_returned_quantity_returnrequest_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancelled_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Partially Cancelled', 'Partially Cancelled'), ('Partially Returned', 'Partially Returned')], default='Ordered', max_length=20),
        ),
    ]
