from django.contrib import admin
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',views.home,name='home'),
    path('login/',views.login_view,name='login'),
    path('signup/',views.signup_view,name='signup'),
    path('verify_otp/<str:username>/', views.verify_otp, name='verify_otp'),
    path('resend_otp/<str:username>/',views.resend_otp,name='resend_otp'),
    path('login_error/',views.login_error,name='login_error'),
    path('password_rest/',auth_views.PasswordResetView.as_view(template_name='user/password_reset.html'),name='password_reset'),
    path('password_reset_done/',auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'),name='password_reset_confirm'),   
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'), name='password_reset_complete'),       
    path('change_password/',views.change_password,name='change_password'),
    path('admin_dashboard/',views.admin_dashboard,name='admin_dashboard'),
    path('user_list/',views.user_list,name='user_list'),
    path('unblock_user/<int:user_id>/',views.unblock_user,name='unblock_user'),
    path('block_user/<int:user_id>/',views.block_user,name='block_user'),
    path('user_dashboard/',views.user_dashboard,name='user_dashboard'),
    path('category/',views.category_list,name='category'),
    path('add_category',views.add_category,name='add_category'),
    path('edit_category/<int:category_id>/', views.edit_category, name='edit_category'),
    path('delete_category/<int:category_id>/',views.delete_category,name='delete_category'),
    path('products',views.product_list,name='products'),
    path('add_product/',views.add_product,name='add_product'),
    path('edit_product/<int:product_id>/',views.edit_product,name='edit_product'),
    path('shop',views.shop,name='shop'),
    path('toggle_product_status/<int:product_id>/',views.toggle_product_status,name='toggle_product_status'),
    path('product/<int:id>/',views.product_details,name='product'),
    path('add_to_cart/<int:product_id>/<int:size>/', views.add_to_cart, name='add_to_cart'),
    path('about/', views.about, name='about'),
    path('contact/',views.contact,name='contact'),
    path('cart/', views.cart, name='cart'),
    path('cart/update-item/', views.update_cart_item, name='update_cart_item'),
    path("apply-coupon/", views.apply_coupon, name="apply_coupon"),
    path('cart/remove/<int:item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('create_order',views.create_order,name='create_order'),
    path('place_order/',views.place_orders,name='place_order'),
    path('cancel_item/<int:item_id>/',views.cancel_item,name='cancel_item'),
    path('download-invoice/<int:order_id>/', views.download_invoice_pdf, name='download_invoice_pdf'),
    path("razorpay/webhook/", views.razorpay_webhook),
    path('payment_success/', views.payment_success, name='payment_success'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('remove_wishlist/<int:id>/',views.remove_wishlist,name='remove_wishlist'),
    path('buy_now/<int:product_id>/<str:size>/', views.buy_now, name='buy_now'),
    path('add_to_wishlist/<int:product_id>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('add_offer',views.add_offer,name='add_offer'),
    path('edit_offer/<int:id>/',views.edit_offer,name='edit_offer'),
    path('delete_offer/<int:id>/',views.delete_offer,name='delete_offer'),
    path('offers_list',views.offers_list,name='offers_list'),
    path('coupon_list/', views.coupon_list, name='coupon_list'),
    path('add_coupon/', views.add_coupon, name='add_coupon'),
    path('edit_coupon/<int:id>/', views.edit_coupon, name='edit_coupon'),
    path('delete-coupon/<int:id>/', views.delete_coupon, name='delete_coupon'),
    path('apply_coupon/',views.apply_coupon,name='apply_coupon'),
    path('checkout/',views.check_out,name='checkout'),
    path('order-confirmation/', views.order_confirmation, name='order_confirmation'),
    path('download-invoice/<int:order_id>/', views.download_invoice_pdf, name='download_invoice_pdf'),
    path('sales-report/', views.sales_report, name='sales_report'),
    path('download-sales-excel/', views.download_sales_excel, name='download_sales_excel'),
    path('download-sales-pdf/', views.download_sales_pdf, name='download_sales_pdf'),
    path('profile/',views.profile_view,name='profile'),
    path('update_profile/',views.update_profile,name='update_profile'),
    path('verify_update_otp/', views.verify_update_otp, name='verify_update_otp'),
    path('resend_update_otp/', views.resend_update_otp, name='resend_update_otp'),
    path('add_address',views.add_address,name='add_address'),
    path('edit_address/<int:address_id>/',views.edit_address,name='edit_address'),
    path('remove_address/<int:address_id>/',views.remove_address,name='remove_address'),
    path("address/set-default/<int:address_id>/", views.set_default_address, name="set_default_address"),
    path('order_list/',views.order_list,name='order_list'),
    path('update-item-status/<int:item_id>/', views.update_item_status, name='update_item_status'),
    path('notifications/', views.notifications_page, name='notifications_page'),
    path('myorders/',views.myorders_view,name='myorders'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    path('return-requests/', views.return_requests, name='return_requests'),
    path('return-requests/<int:request_id>/<str:action>/', views.update_return_status, name='update_return_status'),
    path('stock_list/', views.stock_list, name='stock_list'),
    path('cus_order_details/<int:order_id>/', views.cus_order_details, name='cus_order_details'),
    path("return-item/<int:item_id>/", views.return_item, name="return_item"),
    path('wallet/',views.wallet_view,name='wallet'),
    path('add_money_to_wallet',views.add_money_to_wallet,name='add_money_to_wallet'),
    path('admin_wallet_transactions',views.admin_wallet_transactions,name='admin_wallet_transactions'),
    path('wallet-payment-success/', views.wallet_payment_success, name='wallet_payment_success'),
    path('logout/',views.logout_view,name='logout'),
    path('admin_password_change/', views.admin_change_password, name='admin_change_password'),
]
